# Generated by Django 4.1.7 on 2023-02-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0003_alter_abc_options_remove_abc_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={},
        ),
    ]
