# Generated by Django 4.1.7 on 2023-02-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0004_alter_abc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={'verbose_name': 'A_B_C'},
        ),
    ]
