# Generated by Django 4.1.7 on 2023-02-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0006_alter_abc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='c',
            field=models.IntegerField(default=0, verbose_name='Значение С'),
        ),
    ]
