# Generated by Django 4.1.7 on 2023-03-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0008_alter_abc_options_alter_abc_b_alter_abc_c'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abc',
            options={'ordering': ('-id', 'a'), 'verbose_name': 'A_B_C', 'verbose_name_plural': 'A_B_C_S'},
        ),
    ]
