# Generated by Django 4.1.7 on 2023-04-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0014_alter_abc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='current_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата записи'),
        ),
    ]
