# Generated by Django 4.1.7 on 2023-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0015_alter_abc_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.TextField(default='Равна ли С сумме A и B ?', verbose_name='Формулировка задачи'),
        ),
    ]
