# Generated by Django 4.1.7 on 2023-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0016_alter_abc_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='b',
            field=models.IntegerField(default=0, help_text='Подсказка для поля B', verbose_name='Значение B'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='current_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='Равна ли С сумме A и B ?', max_length=255, verbose_name='Формулировка задачи'),
        ),
    ]
