# Generated by Django 4.1.7 on 2023-04-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0017_alter_abc_b_alter_abc_current_date_alter_abc_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='Равна ли С сумме A и B ?', max_length=255, verbose_name='Формулировка  задачи'),
        ),
    ]
