# Generated by Django 4.1.7 on 2024-03-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0018_alter_abc_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Равна ли С сумме A и B ?', max_length=255, verbose_name='Формулировка  задачи')),
                ('a', models.IntegerField(default=0, verbose_name='Значение А')),
                ('b', models.IntegerField(default=0, help_text='Подсказка для значения B', verbose_name='Значение B')),
                ('c', models.IntegerField(choices=[(0, 'ноль'), (10, 'десять'), (15, 'пятнадцать'), (20, 'двадцать')], default=0, verbose_name='Значение С')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)')),
            ],
            options={
                'verbose_name': 'A_B_C',
                'verbose_name_plural': 'A_B_C_S',
                'ordering': ('-id', '-a'),
            },
        ),
        migrations.DeleteModel(
            name='Abc',
        ),
    ]
