# Generated by Django 4.1.7 on 2024-03-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0020_abcmodel_result_alter_abcmodel_b_alter_abcmodel_c'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abcmodel',
            options={'ordering': ('-id', '-a'), 'verbose_name': 'A_B_C_Таблица', 'verbose_name_plural': 'A_B_C_Таблицы'},
        ),
    ]
